export const roleBased = [
    { name: 'Frontend', id: 'frontend' },
    { name: 'Backend', id: 'backend' },
    { name: 'Full Stack', id: 'fullstack' },
    { name: 'DevOps', id: 'devops' },
    { name: 'Frontend (Beginner)', id: 'frontend-beginner' },
    { name: 'Backend (Beginner)', id: 'backend-beginner' },
    { name: 'DevOps (Beginner)', id: 'devops-beginner' },
    { name: 'Android', id: 'android' },
    { name: 'iOS', id: 'ios' },
    { name: 'PostgreSQL DBA', id: 'postgresql-dba' },
    { name: 'AI Engineer', id: 'ai-engineer' },
    { name: 'Data Analyst', id: 'data-analyst' },
    { name: 'Data Engineer', id: 'data-engineer' },
    { name: 'AI Data Scientist', id: 'ai-data-scientist' },
    { name: 'Machine Learning', id: 'machine-learning' },
    { name: 'Technical Writer', id: 'technical-writer' },
    { name: 'Product Manager', id: 'product-manager' },
    { name: 'QA Engineer', id: 'qa' },
    { name: 'Software Architect', id: 'software-architect' },
    { name: 'Cyber Security', id: 'cyber-security' },
    { name: 'Blockchain', id: 'blockchain' },
    { name: 'Game Developer', id: 'game-developer' },
    { name: 'Server Side Game Dev', id: 'server-side-game-developer' },
    { name: 'UX Design', id: 'ux-design' },
];

export const skillBased = [
    { name: 'Computer Science', id: 'computer-science' },
    { name: 'Data Structures & Algo', id: 'dsa' },
    { name: 'System Design', id: 'system-design' },
    { name: 'Software Architecture', id: 'software-architecture' },
    { name: 'Design System', id: 'design-system' },
    { name: 'API Design', id: 'api-design' },
    { name: 'Prompt Engineering', id: 'prompt-engineering' },
    { name: 'Git & GitHub', id: 'git' },

    { name: 'JavaScript', id: 'javascript' },
    { name: 'TypeScript', id: 'typescript' },
    { name: 'React', id: 'react' },
    { name: 'Next.js', id: 'next.js' },
    { name: 'Vue', id: 'vue' },
    { name: 'Angular', id: 'angular' },
    { name: 'Node.js', id: 'node.js' },
    { name: 'PHP', id: 'php' },
    { name: 'Laravel', id: 'laravel' },
    { name: 'WordPress', id: 'wordpress' },
    { name: 'Spring Boot', id: 'spring-boot' },
    { name: 'ASP.NET Core', id: 'aspnet-core' },
    { name: 'GraphQL', id: 'graphql' },

    { name: 'Python', id: 'python' },
    { name: 'Java', id: 'java' },
    { name: 'Go', id: 'go' },
    { name: 'Rust', id: 'rust' },
    { name: 'C++', id: 'cpp' },
    { name: 'Kotlin', id: 'kotlin' },

    { name: 'SQL', id: 'sql' },
    { name: 'MongoDB', id: 'mongodb' },

    { name: 'Linux', id: 'linux' },
    { name: 'Docker', id: 'docker' },
    { name: 'AWS', id: 'aws' },

    { name: 'Flutter', id: 'flutter' },
    { name: 'React Native', id: 'react-native' },
];
